name: Build-w.yml  
on:  
  workflow_dispatch:  
  
jobs:  
  build:  
    runs-on: windows-latest  
    env:  
      SOLUTION_FILE: WindowsDiskClear.sln  
      PROJECT_FILE: WindowsDiskClear/WindowsDiskClear.csproj  
      CONFIGURATION: Release  
  
    steps:  
    - name: Checkout  
      uses: actions/checkout@v3  
      with:  
        fetch-depth: 0  
  
    - name: Install .NET SDK  
      uses: actions/setup-dotnet@v3  
      with:  
        dotnet-version: '7.0.x' # 请替换为正确的 .NET SDK 版本，例如 '6.0.x' 或 '7.0.x'  
  
    - name: Restore dependencies  
      run: dotnet restore ${{ env.SOLUTION_FILE }}  
  
    - name: Build the application  
      run: dotnet build ${{ env.PROJECT_FILE }} --configuration ${{ env.CONFIGURATION }}  
  
    - name: Execute unit tests  
      run: dotnet test --no-build --configuration ${{ env.CONFIGURATION }}  
  
    - name: Publish  
      run: dotnet publish ${{ env.PROJECT_FILE }} --configuration ${{ env.CONFIGURATION }} --output ./publish  
  
    - name: Upload artifact  
      uses: actions/upload-artifact@v2  
      with:  
        name: my-app-exe  
        path: ./publish/
